### ISSUE TITLE
Fast input of Shift+Numpad makes the Center Input Mode(Shift state) stick

### ISSUE THREAD

**Issue by tchpowdog** [SudokuPad/sudokupad-web-issues#12]
If you hold Shift and enter several digits really fast (on Numpad), let off Shift during or slightly after pressing the digits, the shift state will get stuck.

I had this same issue in my app and the fix was lowering the Shift time threshold required to get around the Shift+Numpad issue.  I lowered mine to 10ms from 50ms.

**Comment by killroy42** [comment]
I cannot reproduce on Chrome/win. Can you please add your OS/browser and verify that it is still an issue?
