### ISSUE TITLE
Request: Lines more visible in colored cells

### ISSUE THREAD

**Issue by cezariuszmarek** [SudokuPad/sudokupad-web-issues#24]
When there is a gray line or arrow in a cell, and the call is colored (especially in pink or orange), the line is hardly visible:

![image](https://user-images.githubusercontent.com/9655758/190922482-03a22804-b93a-41d4-8150-c6fa85c2511c.png)

It would be nice if you could add an outline to the line, to make it look better on all colors. It could be even white, so it won't change the look on white cells, but will add a sort of the shadow on colored cells, like this:

![image](https://user-images.githubusercontent.com/9655758/190922568-22f2478f-407f-4d19-97c4-863ed54f0785.png)

**Comment by ewenmcneill** [comment]
I think this might have been implemented in the last year.   At least in June 2023 sudokupad.app when I shade an arrow puzzle with orange there is a thin strip of white either side of the grey arrow line.

So possibly this issue can be closed now?

Ewen

**Comment by cezariuszmarek** [comment]
Yes, I think it has been implemented since the original request report.
